version: '3.7'
services:
  postgres:
    container_name: pg_container
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/pgdata

  backend:
    build:
      context: ./backend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./backend:/go/src/github.com/user/GoDoRP/api
    env_file: ./backend/.env
    ports:
      - "5000:8080"
    links:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend/src:/frontend/src 
    ports:
      - "3000:3000"