version: '3.7'
services:
  postgres:
    container_name: pg_container
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/pgdata

  app:
    build:
      context: ./
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./:/go/src/GoDoRP
    env_file: ./.env
    ports:
      - "8080:8080"
    links:
      - postgres
