openapi: 3.0.0
info:
  version: 0.0.1
  title: learn godorp
servers:
  - url: 'http://localhost:8080/api/auth'
paths:
  /register:
    post:
      summary: 'register a new account'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: 'new user created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  result:
                    type: object
                    items:
                      $ref: '#/components/schemas/User'
  /login:
    post:
      summary: 'login'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
          '200':
            description: 'login success'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                    result:
                      type: object
                      items: 
                        $ref: '#/components/schemas/LoginResponse'
          '400':
            description: 'incorrect password'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                    result:
                      type: object
          '404':
            description: 'user not found'
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                    result:
                      type: object
  /user:
    get:
      security:
        - cookieAuth: []
      summary: 'get current login user'
      operationId: listUser
      tags:
        - user
      responses:
        '200':
          description: 'details about the user'
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  result:
                    type: object
                    items:
                      $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    RegisterUser:
      type: object
      required:
        - firstName
        - lastName
        - email
        - password
        - confirmPass
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          example: bing5@dep.chai
        password:
          type: string
          example: Bingvip69
        confirmPass:
          type: string
          example: Bingvip69
    LoginUser:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: bing@dep.chai
        password:
          type: string
          example: Bingvip69.
    LoginResponse:
      type: object
      required:
        - jwt
      properties:
        jwt:
          type: string
    User:
      type: object
      required:
        - firstName
        - lastName
        - email
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        confirmPass:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt